In [25]:
## fancyimpute requires TensorFlow
import pandas as pd
pd.options.display.max_columns=100
import numpy as np
import argparse
from directory import data

In [238]:
clean = pd.read_pickle("{}/clean.pkl".format(data))
clean.head()

,age_median2017,structure_year_median2017,percent_race_white2017,percent_race_black2017,percent_poverty_2017,percent_tenure_owner2017,percent_occupancy_vacant2017,percent_housing_units_mobile2017,percent_single_unit_housing2017,percent_bachelorsplus2017,percent_enrolled2017,change_population_total,change_household_income_median,change_home_value_median,change_housing_units_total,geoid,oz,LICadj,eligible
0,40.6,1986.0,0.938328,0.061672,0.068483,0.849352,0.262691,0.406930,0.563255,0.208609,0.030048,-0.116644,0.132551,0.216069,0.044613,01007010001,0,0,1
1,35.9,1990.0,0.942751,0.048863,0.256249,0.682429,0.218232,0.342147,0.589582,0.111001,0.027598,0.016724,-0.041367,0.003024,0.071006,01007010002,1,0,1
2,41.8,1986.0,0.811804,0.176868,0.114269,0.852544,0.262687,0.225586,0.773134,0.187554,0.061532,0.005395,0.626031,0.362416,0.009905,01007010003,0,1,1
3,39.4,1979.0,0.564338,0.416245,0.090533,0.683401,0.234291,0.207553,0.657086,0.094574,0.041681,0.003574,0.207643,0.167532,-0.029202,01007010004,0,0,1
4,34.9,1973.0,0.008902,0.988872,0.273739,0.488131,0.380859,0.047852,0.732422,0.249154,0.098398,-0.163253,0.382493,-0.030266,-0.069936,01087231900,0,0,1